plugins {
    id 'java'
    id "com.vanniktech.maven.publish" version "0.30.0" apply false
}

allprojects {
    group = 'net.kumbhar.dx'
    version = '2.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
        withJavadocJar()
        withSourcesJar()
    }

    base {
        archivesName = "record-hacks-${project.name}"
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    test {
        useJUnitPlatform()
    }
}

project(':annotations') {
    apply plugin: 'java-library'
    apply plugin: "com.vanniktech.maven.publish"

    mavenPublishing {
        coordinates("net.kumbhar.dx", "record-hacks-annotations", version)

        pom {
            name = 'record-hacks-annotations'
            description = 'record-hacks is a Java library that will help you track "creative solutions" in your code.'
            url = 'https://github.com/rohitkumbhar/record-hacks'
            licenses {
                license {
                    name = 'MIT License'
                    url = 'https://github.com/rohitkumbhar/record-hacks/blob/master/LICENSE'
                }
            }
            developers {
                developer {
                    id = 'rohitkumbhar'
                    name = 'Rohit Kumbhar'
                    email = 'rohit@kumbhar.net'
                }
            }
            scm {
                connection = 'scm:git:https://github.com/rohitkumbhar/record-hacks.git'
                developerConnection = 'scm:git:https://github.com/rohitkumbhar/record-hacks.git'
                url = 'https://github.com/rohitkumbhar/record-hacks'
            }
        }

        publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.DEFAULT)
        signAllPublications()
    }
}

project(':tests') {
    dependencies {
        implementation project(':annotations')
        annotationProcessor project(':annotations')
    }
}